bounswe/bounswe2024group3

bibliosearch_web/src/components/SvgIcon.tsx
bibliosearch_web/src/pages/LoginPage.tsx
bibliosearch_web/src/pages/RegisterPage.tsx

SvgIcon component added in order to prevent repeated code blocs
closes  #111

Adds SvgIcon component

---

bibliosearch_backend/requirements.txt

I have added requests to the requirements.txt. It is used in wikidata_client.

Added requests to the requirements.txt

---

bibliosearch_web/src/components/Header.tsx
bibliosearch_web/src/components/NavbarAccount.tsx
bibliosearch_web/src/index.tsx
bibliosearch_web/src/pages/LoginPage.tsx
bibliosearch_web/src/pages/RegisterPage.tsx
bibliosearch_web/src/providers/UserContest.tsx

Add react context for storing user data

---

bibliosearch_backend/.dockerignore
bibliosearch_backend/Dockerfile
bibliosearch_backend/bibliosearch_backend/settings.py
bibliosearch_backend/bibliosearch_backend/urls.py
bibliosearch_web/.dockerignore
bibliosearch_web/Dockerfile
docker-compose/backend.yml
docker-compose/db.yml
docker-compose/docker-compose.yml
docker-compose/frontend.yml
docker-compose/nginx.yml
docker-compose/proxy/default.conf.template

creates containers:
- backend
- fronentd
- nginx
- database

dockerize web and backend

---

bibliosearch_backend/bibliosearch_backend/urls.py

I updated the urls.py so that the book search endpoint is book/search/ now instead of searchBook/

updated urls.py so that the book search endpoint is book/search/

---

bibliosearch_backend/api/views.py

I have changed the endpoint's body format so that it takes the book data under "book_data" key.

changed the body format

---

bibliosearch_backend/bibliosearch_backend/settings.py
bibliosearch_web/src/components/BookCard.tsx
bibliosearch_web/src/index.tsx
bibliosearch_web/src/pages/BookPage.tsx
bibliosearch_web/src/pages/FeedPage.tsx
bibliosearch_web/src/pages/LoginPage.tsx

Add book page routing

---

bibliosearch_backend/api/views.py
bibliosearch_backend/bibliosearch_backend/urls.py

I have implemented the create_book endpoint.

implemented the create_book endpoint

---

bibliosearch_web/src/components/UserCard.tsx
bibliosearch_web/src/index.tsx
bibliosearch_web/src/pages/SearchUserPage.tsx
bibliosearch_web/src/pages/UserProfile.tsx

add follow

---

bibliosearch_web/src/pages/Profile.tsx

Add booklist creation

---

bibliosearch_web/src/components/AddToBooklist.tsx
bibliosearch_web/src/components/BookCard.tsx
bibliosearch_web/src/pages/Profile.tsx

[WIP] Implement Add to booklist popup

---

bibliosearch_mobile/App.js
bibliosearch_mobile/screens/BookPage.js
bibliosearch_mobile/screens/Landing.js
bibliosearch_mobile/screens/MainPage.js
bibliosearch_mobile/screens/ProfileScreen.js
bibliosearch_mobile/screens/RegistrationScreen.js

Created profile screen for the user to be able to see their profile and update it. 
Also introduced a new colour palette. 
Added UX improvements.

Created profile screen 

---

bibliosearch_mobile/screens/CreatePost.js
bibliosearch_mobile/screens/FeedPage.js

Created a feed page and a create post button that allows for creation of new posts. 
But endpoints were not connected yet.

Started the implementation creating posts for feed.

---

web/src/pages/LoginPage.tsx

create login page

---

web/src/pages/RegisterPage.tsx

add register page

---

web/src/App.tsx
web/src/components/Layout.tsx
web/src/index.tsx

add routes and layout

---

web/.gitignore
web/src/pages/LoginPage.tsx
web/src/pages/RegisterPage.tsx
web/src/utils/client.tsx

add axios request handler

---

web/package-lock.json
web/package.json

Add axios as dependancy

---

web/src/App.tsx
web/src/components/Header.tsx
web/src/components/NavbarAccount.tsx
web/src/components/PostCard.tsx
web/src/index.tsx
web/src/pages/LoginPage.tsx
web/src/pages/PostPage.tsx
web/src/providers/UserContext.tsx

add user context functionality

---

web/src/components/RecommendationItem.tsx

fix logout bug

---

mobile/app-example/(tabs)/_layout.tsx
mobile/app/_layout.tsx
mobile/app/profile.tsx
mobile/app/search.tsx
mobile/components/PostCard.tsx

I have also commented out app-example's navigation since react native does not allow nested nevigation components.
Currently the navbar colors are red but we should change them in the future when we have a color palette for SpotOn.

Implement navbar and placeholder search and profile pages.

---

mobile/app/(auth)/login.tsx
mobile/app/(auth)/register.tsx

Simple ui modifiactions and extra role selection has been added.

Add username and role selection to register and forgot password to login

---

web/src/App.tsx
web/src/components/Accessibility.tsx
web/src/components/Header.tsx
web/src/components/NavbarAccount.tsx

Creation Of Accessibility Component and implementation in header for Web Standards

Accessibility for Web Standards

---

web/src/components/LocationFetcher.tsx
web/src/pages/LoginPage.tsx

Addition of the LocationFetcher and all the funtionality to work when an User logs in

LocationFetcher

---

web/jest.config.js
web/package-lock.json
web/package.json
web/src/utils/client.test.tsx

Add jest as dev dependency and Add req test

---

web/src/components/LocationFetcher.tsx
web/src/pages/LoginPage.tsx
web/src/providers/UserContext.tsx

fix location fetch closes #444

---

web/src/components/CreatePostForm.tsx
web/src/pages/PostPage.tsx

Fix post creating ui

---

web/src/pages/FeedPage.tsx

add most listened nearby bar

---

web/src/pages/PostPage.tsx

I currently mocked the recommendations with the latest posted tracks
Closes #397

Add recommendations

---

mobile/app/(tabs)/recommendations.tsx
mobile/app/(tabs)/search.tsx

Enes abdullah/recommendation search

---

mobile/app/(tabs)/search.test.tsx

Add unit tests for search

---

web/src/components/Accessibility.tsx
web/src/pages/FeedPage.tsx
web/src/pages/SearchPage.tsx

Fix context

---

backend/api/views.py
backend/music_app/urls.py

Added fetching random songs based on filters from spotyfy

added random songs

---

backend/requirements.txt
docker-compose/backend-only-docker-compose.yml
docker-compose/docker-compose.yml

fix the requirements, and docker files closes #521

---

web/src/components/LyricsCard.tsx
web/src/components/PostCard.tsx
web/src/pages/PostPage.tsx

add lyrics component

---

web/src/pages/PostPage.tsx

fix most listened

---

backend/api/views.py

Closes #541
Beware that what the endpoint returns is updated since the content model is updated.

Updated where search looks.

---

mobile/components/PostCard.tsx

show/hide lyrics button added the Post component.

---

backend/api/views.py
backend/music_app/urls.py

The endpoint that returns the last liked songs by a user is implemented.

Get Liked Songs

---

backend/api/views.py
web/src/pages/FeedPage.tsx

add following tab to feed page

---

mobile/app/profile/[username].tsx
mobile/components/PostCard.tsx
mobile/tsconfig.json

User profile screen created dynamically.

---

mobile/app/profile/[username].tsx
mobile/tsconfig.json

follow unfollow functionality is working correctly.

---

mobile/app/(tabs)/MostListenedNearby.test.tsx

Unit tests for Most Listened/Shared Nearby Screen added.

---

mobile/app/(tabs)/SongQuizScreen.test.tsx

Unit tests for Song Quiz Screen added.

---

mobile/app/(tabs)/index.tsx

get following posts.

---

web/src/pages/FeedPage.tsx

Add pagination on feed page

---

web/src/components/Header.tsx
web/src/components/QuizComponent.tsx

Improve quiz page and add to navbar

---

web/src/pages/PostPage.tsx

Fix lyrics bar width

---

backend/api/views.py

there was a import error that we didnt use and didnt wrote to requirements.txt.

fixed import error
